### ISSUE TITLE
ink-generator-python on Mac OS X

### ISSUE THREAD

**Issue by jeduar** [butesa/ink-generator-python#1]
Hi

I was searching for this utility and I found original and your version later... the first one was detected but didn't handle special characters... Yours doesn't seem to show in Inkscape. extensions menu, and indeed you don't give instructions to install it on a Mac. If you need some testing I can provide testing time. I have tried to execute from the command line... But it fails...

/generator.py --vartype NAME --datafile /Users/edu/Downloads/SOCIOS.csv --format PNG --dpi 90 --output /Users/edu/Pictures/%VAR_apellido%-carnet.png  --specialchars TRUE /Users/edu/Pictures/CarnetSocioZZFT-modelo.svg

It breaks here:
raceback (most recent call last):
  File "./generator.py", line 362, in <module>
    Process_csv_file(csvfile)
  File "./generator.py", line 328, in Process_csv_file
    Generate(row)
  File "./generator.py", line 207, in Generate
    Ink_render(tmp_svg, destfile, globaldata.args.format)
  File "./generator.py", line 222, in Ink_render
    'Inkscape Converting Error')
  File "./generator.py", line 294, in Call_or_die
    subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Best regards

Eduardo

**Comment by butesa** [comment]
Hello,

I don't have a Mac, so I can't say much about the installation on a Mac, but there should also be a extensions folder where you can put your files in.

I think this error happens because the script can't find the inkscape executable. What happens when you enter `inkscape` on the command line?

Best regards
butesa

**Comment by jeduar** [comment]
Hi

I have checked, you where right. I have added Inkscape's folder  to the PATH. I have also uncommented line 337 

globaldata.tempdir = tempfile.mkdtemp()

because I got an error in the line 356. of the .py file. 

shutil.rmtree(globaldata.tempdir)

Now Inkscape starts but it doesn't open the sag file. This os the actual command line (al file references are correctly setup=

/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/generator.py --vartype NAME --datafile /Users/edu/Downloads/Libro2.csv --format PNG --dpi 90 --output /Users/edu/Pictures/%VAR_apellido1%.png  --specialchars TRUE /Users/edu/Pictures/CarnetSocioZZFT-modelo.svg

Thanks you for your time.

Eduardo

**Comment by butesa** [comment]
Hello,

what do you mean by "Now Inkscape starts"? You shouldn't see inkscape at all, it should only do its work in the background.

What results do you get when you enter the following command in the command line?
`inkscape --without-gui --export-png="/Users/edu/Pictures/test.png" --export-dpi=90 "/Users/edu/Pictures/CarnetSocioZZFT-modelo.svg"`

Best regards
butesa

**Comment by jeduar** [comment]
Hi
The problem was that, the default binary, the one is used in the gun and that spawns doesn't have the command line available. For this you must use /Applications/Inkscape.app/Contents/Resources/bin/inkscape-bin, instead of /Applications/Inkscape.app/Contents/MacOS/Inkscape

Best regards
Eduardo

**Comment by butesa** [comment]
Hello

is this issue resolved for you or do you need additional help?

Best regards
butesa

**Comment by jeduar** [comment]
Hi

Now, it still doesn't work. At this moment, I think I will just search a windows/linux machine to use it... I need it for a low priority/hobbyist task and I don't have much time... Perhaps I'll be back on the topic.

Thank you for your time.

Eduardo
