### ISSUE TITLE
Problema con caracteres acentuados

### ISSUE THREAD

**Issue by danielgasparpereira** [butesa/ink-generator-python#2]
Hola,

Al incluir en el CSV caracteres con acento como "**á é í ó ú**" o "**ñ Ñ**" no los reconoce. En el resultado aparece un símbolo con signos de interrogación.

¿Alguna sugerencia? 

Gracias.

**Comment by butesa** [comment]
Hello,

please use UTF-8 encoding in your CSV file.

Best regards
butesa
