### ISSUE TITLE
If there are spaces at the start of csv's column names var will not match

### ISSUE THREAD

**Issue by federicosan** [butesa/ink-generator-python#3]
Problem
The example csv file downloded from inkscape website has spaces after comas, this spaces would won't match the variable names on template.

Fix

Delete the spaces from column names after comas, for example lik this

name,occupation,someothervariable,

The plugin, could be fixed to check for this by trimming column names.

**Comment by butesa** [comment]
I would rather fix the example csv file. Can you please post the URL to the file you mentioned?

**Comment by federicosan** [comment]
Hi, https://inkscape.org/es/~Moini/%E2%98%85example-files-for-generator-extension   in this example the file generator-example.csv has spaces after each comma in all column names after the first. So running the example only renders files where name is the only variable being replaced, that is because the script can't find occupation because it finds " occupation"

**Comment by butesa** [comment]
In my opinion, this is a bug in the bash version of Generator. If you don't want to have spaces in your column name, you should not include spaces in your csv file. So I'm not going to fix this.

**Comment by butesa** [comment]
Hello,

I added a modified version of the example files to this repository.
